// app/category/electronics/page.jsx
import CategoryBanner from '@/app/components/CategoryBanner';
import ProductListing from '@/app/components/ProductListing';

export const metadata = {
  title: 'Electronics - Smartphones, Laptops, Gadgets & More | Vangmaya',
  description: 'Shop the latest electronics including smartphones, laptops, tablets, headphones, smartwatches, and more at best prices. Fast delivery across India.',
  keywords: 'electronics, smartphones, laptops, gadgets, headphones, smartwatch, india, online shopping',
  openGraph: {
    title: 'Electronics - Best Deals on Gadgets | Vangmaya',
    description: 'Discover amazing deals on electronics. Shop smartphones, laptops, and more.',
    type: 'website',
  },
};

// Mock electronics products data
const electronicsProducts = [
  {
    id: 1,
    name: 'iPhone 15 Pro Max 256GB - Natural Titanium',
    price: 156900,
    originalPrice: 169900,
    discount: 8,
    rating: 4.8,
    reviews: 12547,
    image: '/images/products/electronics/iphone-15-pro.jpg',
    badge: 'Bestseller',
    brand: 'Apple',
    inStock: true,
  },
  {
    id: 2,
    name: 'Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB)',
    price: 129999,
    originalPrice: 144999,
    discount: 10,
    rating: 4.7,
    reviews: 8934,
    image: '/images/products/electronics/samsung-s24.jpg',
    badge: 'Top Rated',
    brand: 'Samsung',
    inStock: true,
  },
  {
    id: 3,
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    price: 26990,
    originalPrice: 34990,
    discount: 23,
    rating: 4.9,
    reviews: 6721,
    image: '/images/products/electronics/sony-headphones.jpg',
    badge: 'Best Deal',
    brand: 'Sony',
    inStock: true,
  },
  {
    id: 4,
    name: 'MacBook Air M3 Chip 13-inch (8GB RAM, 256GB SSD)',
    price: 104900,
    originalPrice: 114900,
    discount: 9,
    rating: 4.8,
    reviews: 4532,
    image: '/images/products/electronics/macbook-air.jpg',
    badge: 'New',
    brand: 'Apple',
    inStock: true,
  },
  {
    id: 5,
    name: 'OnePlus 12 5G (16GB RAM, 512GB Storage)',
    price: 69999,
    originalPrice: 74999,
    discount: 7,
    rating: 4.6,
    reviews: 5678,
    image: '/images/products/electronics/oneplus-12.jpg',
    badge: null,
    brand: 'OnePlus',
    inStock: true,
  },
  {
    id: 6,
    name: 'Apple Watch Series 9 GPS 45mm Aluminum Case',
    price: 41900,
    originalPrice: 44900,
    discount: 7,
    rating: 4.7,
    reviews: 3421,
    image: '/images/products/electronics/apple-watch.jpg',
    badge: null,
    brand: 'Apple',
    inStock: true,
  },
  {
    id: 7,
    name: 'boAt Airdopes 141 Bluetooth Truly Wireless Earbuds',
    price: 1299,
    originalPrice: 4490,
    discount: 71,
    rating: 4.1,
    reviews: 156789,
    image: '/images/products/electronics/boat-airdopes.jpg',
    badge: 'Bestseller',
    brand: 'boAt',
    inStock: true,
  },
  {
    id: 8,
    name: 'Dell Inspiron 15 Laptop (i5 13th Gen, 16GB, 512GB SSD)',
    price: 62990,
    originalPrice: 78990,
    discount: 20,
    rating: 4.4,
    reviews: 2345,
    image: '/images/products/electronics/dell-laptop.jpg',
    badge: null,
    brand: 'Dell',
    inStock: true,
  },
  {
    id: 9,
    name: 'Realme Narzo 70 Pro 5G (8GB RAM, 128GB)',
    price: 19999,
    originalPrice: 24999,
    discount: 20,
    rating: 4.3,
    reviews: 4521,
    image: '/images/products/electronics/realme-narzo.jpg',
    badge: 'Value Pick',
    brand: 'Realme',
    inStock: true,
  },
  {
    id: 10,
    name: 'JBL Flip 6 Portable Bluetooth Speaker',
    price: 11999,
    originalPrice: 14999,
    discount: 20,
    rating: 4.5,
    reviews: 8765,
    image: '/images/products/electronics/jbl-flip.jpg',
    badge: null,
    brand: 'JBL',
    inStock: true,
  },
  {
    id: 11,
    name: 'Samsung 55" Crystal 4K Neo UHD Smart TV',
    price: 47990,
    originalPrice: 64990,
    discount: 26,
    rating: 4.4,
    reviews: 3210,
    image: '/images/products/electronics/samsung-tv.jpg',
    badge: 'Best Deal',
    brand: 'Samsung',
    inStock: true,
  },
  {
    id: 12,
    name: 'iPad Air (5th Gen) 10.9-inch Wi-Fi 64GB',
    price: 54900,
    originalPrice: 59900,
    discount: 8,
    rating: 4.8,
    reviews: 2876,
    image: '/images/products/electronics/ipad-air.jpg',
    badge: null,
    brand: 'Apple',
    inStock: false,
  },
  {
    id: 13,
    name: 'Noise ColorFit Pro 5 Max Smartwatch AMOLED Display',
    price: 4999,
    originalPrice: 8999,
    discount: 44,
    rating: 4.2,
    reviews: 12456,
    image: '/images/products/electronics/noise-watch.jpg',
    badge: 'Popular',
    brand: 'Noise',
    inStock: true,
  },
  {
    id: 14,
    name: 'Canon EOS R50 Mirrorless Camera with 18-45mm Lens',
    price: 71990,
    originalPrice: 79990,
    discount: 10,
    rating: 4.6,
    reviews: 876,
    image: '/images/products/electronics/canon-camera.jpg',
    badge: null,
    brand: 'Canon',
    inStock: true,
  },
  {
    id: 15,
    name: 'Logitech MX Master 3S Wireless Mouse',
    price: 9495,
    originalPrice: 10995,
    discount: 14,
    rating: 4.7,
    reviews: 2345,
    image: '/images/products/electronics/logitech-mouse.jpg',
    badge: null,
    brand: 'Logitech',
    inStock: true,
  },
  {
    id: 16,
    name: 'Anker 735 Charger GaNPrime 65W Fast Charging',
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    rating: 4.5,
    reviews: 5678,
    image: '/images/products/electronics/anker-charger.jpg',
    badge: null,
    brand: 'Anker',
    inStock: true,
  },
];

const categoryInfo = {
  name: 'Electronics',
  description: 'Discover the latest smartphones, laptops, tablets, wearables, audio devices, and more. Shop top brands at unbeatable prices with fast delivery.',
  image: '/images/banners/electronics-banner.jpg',
  totalProducts: 2847,
};

const filterOptions = {
  brands: ['Apple', 'Samsung', 'Sony', 'OnePlus', 'Dell', 'boAt', 'JBL', 'Realme', 'Noise', 'Canon', 'Logitech', 'Anker'],
  priceRanges: [
    { label: 'Under ₹1,000', min: 0, max: 1000 },
    { label: '₹1,000 - ₹5,000', min: 1000, max: 5000 },
    { label: '₹5,000 - ₹15,000', min: 5000, max: 15000 },
    { label: '₹15,000 - ₹30,000', min: 15000, max: 30000 },
    { label: '₹30,000 - ₹50,000', min: 30000, max: 50000 },
    { label: '₹50,000 - ₹1,00,000', min: 50000, max: 100000 },
    { label: 'Above ₹1,00,000', min: 100000, max: Infinity },
  ],
  subcategories: [
    'Smartphones',
    'Laptops',
    'Tablets',
    'Headphones & Earbuds',
    'Smartwatches',
    'Speakers',
    'Televisions',
    'Cameras',
    'Accessories',
  ],
  ratings: [4, 3, 2, 1],
  discounts: [
    { label: '10% or more', value: 10 },
    { label: '20% or more', value: 20 },
    { label: '30% or more', value: 30 },
    { label: '50% or more', value: 50 },
  ],
};

export default function ElectronicsPage() {
  return (
    <>
      <main className="category-page">
        <CategoryBanner category={categoryInfo} />
        <ProductListing 
          products={electronicsProducts} 
          filters={filterOptions}
          categoryName="Electronics"
        />
      </main>
    </>
  );
}
